### ISSUE TITLE
Mvc-ef Migration

### ISSUE THREAD

**Issue by cevarief** [kerryjiang/dotnetcore-samples#2]
Hi, it's me again.

Does it work to create migration `dotnet ef migrations add Init` using mvc-ef sample ?

``` bash
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentNullException: Value cannot be null.
Parameter name: assemblyName
   at System.Reflection.AssemblyName..ctor(String assemblyName)
```

**Comment by kerryjiang** [comment]
Do you mean automatic migration?

From [the sample of ASP.NET Identity](https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Startup.cs), there might be one piece of code required:

```
using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
                        .CreateScope())
{
            serviceScope.ServiceProvider.GetService<ApplicationDbContext>()
                             .Database.Migrate();
 }
```

**Comment by cevarief** [comment]
I mean code first migrations using ef tools.

``` json
"tools": {
    "dotnet-ef": {
      "version": "1.0.0-*",
      "imports": [
        "portable-net45+wp80+win8+wpa81+dnxcore50",
        "portable-net45+win8+wp8+wpa81",
        "portable-net45+win8+wp8"
      ]
    }
  },
...
```

**Comment by kerryjiang** [comment]
I think you need pass in the connectionString somewhere then the tool can compare the db schema.
The DbContext in .net core doesn't bind a connection string in configuration like .NET does.

**Comment by cevarief** [comment]
It's now using Microsoft.EntityFrameworkCore.Tools. [EF Issue](https://github.com/aspnet/EntityFramework/issues/3925#issue-119549607)
